In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\4005\Downloads\sosang\sosangin.csv')

C:\Users\4005\AppData\Local\Temp\ipykernel_19544\3973733574.py:1: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r'C:\Users\4005\Downloads\sosang\sosangin.csv')

In [3]:
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0089715,날으는뚝배기원창점,NaN,I2,음식,I201,한식,I20102,국/탕/찌개류,I56111,...,2826011100103810048000001,건원프라자,인천광역시 서구 북항로32번안길 41,404210,22769,NaN,NaN,NaN,126.646684,37.509518
1,MA010120220805430815,아기숟가락,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56194,...,2818510600100830000000001,송도센트럴파크푸르지오시티,인천광역시 연수구 아트센터대로 203,406840,22008,NaN,1,NaN,126.631272,37.395189
2,MA010120220805430978,러블리헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,2820010200106170024006353,신원아침도시비,인천광역시 남동구 경원대로 962,405810,21502,NaN,1,NaN,126.690749,37.468792
3,MA010120220805430761,쉐프윤,NaN,I2,음식,I210,기타 간이,I21003,피자,I56192,...,2817010100100450003125288,NaN,인천광역시 미추홀구 수봉로 20,402812,22163,NaN,NaN,NaN,126.656146,37.464376
4,MA010120220805430901,The선재로59Street,NaN,I1,숙박,I101,일반 숙박,I10104,캠핑/글램핑,I55109,...,2872036023101500000000001,NaN,인천광역시 옹진군 영흥면 선재로 59,409872,23123,NaN,NaN,NaN,126.531273,37.234406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113656,MA0101202307A0013333,상큼한과일,NaN,G2,소매,G205,식료품 소매,G20506,채소/과일 소매업,G47215,...,2817010100106330025125031,NaN,인천광역시 미추홀구 경인로 126,402812,22164,NaN,1,NaN,126.656672,37.465959
113657,MA0101202307A0023409,힐링,NaN,G2,소매,G215,의약·화장품 소매,G21503,화장품 소매업,G47813,...,2824510200110630004176960,두손파스텔,인천광역시 계양구 계산새로65번길 9,407813,21060,NaN,NaN,NaN,126.735211,37.539097
113658,MA0101202307A0106428,석남마사지,NaN,S2,수리·개인,S208,욕탕·신체관리,S20803,체형/비만 관리,S96129,...,2826011000105910013018226,NaN,인천광역시 서구 석남로 70-1,404829,22795,NaN,2,NaN,126.669370,37.500810
113659,MA0101202307A0024831,아수라떡볶이,NaN,I2,음식,I210,기타 간이,I21007,김밥/만두/분식,I56111,...,2817010500100940001061684,NaN,인천광역시 미추홀구 석정로 228,402806,22102,NaN,1,NaN,126.660830,37.467961
113660,MA0101202307A0045892,정석갈비,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56111,...,2826011400110810002000001,NaN,인천광역시 서구 청마로51번안길 18,404310,22675,NaN,1,NaN,126.672487,37.591650

In [4]:
df.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [5]:
df.head()

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0089715,날으는뚝배기원창점,NaN,I2,음식,I201,한식,I20102,국/탕/찌개류,I56111,...,2826011100103810048000001,건원프라자,인천광역시 서구 북항로32번안길 41,404210,22769,NaN,NaN,NaN,126.646684,37.509518
1,MA010120220805430815,아기숟가락,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56194,...,2818510600100830000000001,송도센트럴파크푸르지오시티,인천광역시 연수구 아트센터대로 203,406840,22008,NaN,1,NaN,126.631272,37.395189
2,MA010120220805430978,러블리헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,...,2820010200106170024006353,신원아침도시비,인천광역시 남동구 경원대로 962,405810,21502,NaN,1,NaN,126.690749,37.468792
3,MA010120220805430761,쉐프윤,NaN,I2,음식,I210,기타 간이,I21003,피자,I56192,...,2817010100100450003125288,NaN,인천광역시 미추홀구 수봉로 20,402812,22163,NaN,NaN,NaN,126.656146,37.464376
4,MA010120220805430901,The선재로59Street,NaN,I1,숙박,I101,일반 숙박,I10104,캠핑/글램핑,I55109,...,2872036023101500000000001,NaN,인천광역시 옹진군 영흥면 선재로 59,409872,23123,NaN,NaN,NaN,126.531273,37.234406

In [6]:
df[['상권업종대분류명','상권업종중분류명','상권업종소분류명']]

       상권업종대분류명   상권업종중분류명   상권업종소분류명
0            음식         한식    국/탕/찌개류
1            음식         한식     국수/칼국수
2         수리·개인      이용·미용        미용실
3            음식      기타 간이         피자
4            숙박      일반 숙박     캠핑/글램핑
...         ...        ...        ...
113656       소매     식료품 소매  채소/과일 소매업
113657       소매  의약·화장품 소매    화장품 소매업
113658    수리·개인    욕탕·신체관리   체형/비만 관리
113659       음식      기타 간이   김밥/만두/분식
113660       음식         한식  돼지고기 구이/찜

[113661 rows x 3 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113661 entries, 0 to 113660
Data columns (total 39 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   상가업소번호     113661 non-null  object
 1   상호명        113661 non-null  object
 2   지점명        1772 non-null    object
 3   상권업종대분류코드  113661 non-null  object
 4   상권업종대분류명   113661 non-null  object
 5   상권업종중분류코드  113661 non-null  object
 6   상권업종중분류명   113661 non-null  object
 7   상권업종소분류코드  113661 non-null  object
 8   상권업종소분류명   113661 non-null  object
 9   표준산업분류코드   113651 non-null  object
 10  표준산업분류명    113651 non-null  object
 11  시도코드       113661 non-null  int64
 12  시도명        113661 non-null  object
 13  시군구코드      113661 non-null  int64
 14  시군구명       113661 non-null  object
 15  행정동코드      113661 non-null  int64
 16  행정동명       113661 non-null  object
 17  법정동코드      113661 non-null  int64
 18  법정동명       113661 non-null  object
 19  지번코드       113661 non-null  int64
 20  대지구분코드     113661 non-null  int64
 21  대지구분명      113661 non-null  object
 22  지번본번지      113536 non-null  float64
 23  지번부번지      98746 non-null   float64
 24  지번주소       113661 non-null  object
 25  도로명코드      113661 non-null  int64
 26  도로명        113661 non-null  object
 27  건물본번지      113661 non-null  int64
 28  건물부번지      17449 non-null   float64
 29  건물관리번호     113649 non-null  object
 30  건물명        50091 non-null   object
 31  도로명주소      113661 non-null  object
 32  구우편번호      113661 non-null  int64
 33  신우편번호      113661 non-null  int64
 34  동정보        0 non-null       float64
 35  층정보        61887 non-null   object
 36  호정보        0 non-null       float64
 37  경도         113661 non-null  float64
 38  위도         113661 non-null  float64
dtypes: float64(7), int64(10), object(22)
memory usage: 33.8+ MB

In [8]:
null_sum = df.isnull().sum()

In [9]:
null_df = null_sum.reset_index

In [10]:
df.groupby('상권업종대분류명')['상권업종중분류명'].count().sort_values(ascending=False)

상권업종대분류명
음식         38500
소매         27795
수리·개인      14060
과학·기술       9155
예술·스포츠      6294
부동산         5244
교육          4618
시설관리·임대     4073
숙박          2672
보건의료        1250
Name: 상권업종중분류명, dtype: int64

In [11]:
category_a = set(df['상권업종대분류명'])
category_a, len(category_a) # 대분류 총 10가지

({'과학·기술',
  '교육',
  '보건의료',
  '부동산',
  '소매',
  '수리·개인',
  '숙박',
  '시설관리·임대',
  '예술·스포츠',
  '음식'},
 10)

In [12]:
category_b = set(df['상권업종중분류명'])
category_b, len(category_b) # 중분류 총 75가지

({'가구 소매',
  '가전·통신 소매',
  '가전제품 수리',
  '가정용품 대여',
  '고용 알선',
  '광고',
  '교육 지원',
  '구내식당·뷔페',
  '기술 서비스',
  '기타 가정용품 수리',
  '기타 간이',
  '기타 개인',
  '기타 교육',
  '기타 보건',
  '기타 사업 서비스',
  '기타 상품 소매',
  '기타 생활용품 소매',
  '기타 숙박',
  '기타 외국',
  '기타 전문 과학',
  '담배 소매',
  '도서관·사적지',
  '동남아시아',
  '모터사이클 소매',
  '모터사이클 수리',
  '법무관련 ',
  '병원',
  '본사·경영 컨설팅',
  '부동산 서비스',
  '비알코올 ',
  '사무 지원',
  '사진 촬영',
  '산업용품 대여',
  '서양식',
  '섬유·의복·신발 소매',
  '세탁',
  '수의',
  '스포츠 서비스',
  '시계·귀금속 소매',
  '시설관리',
  '시장 조사',
  '식료품 소매',
  '식물 소매',
  '안경·정밀기기 소매',
  '애완동물·용품 소매',
  '여행사·보조',
  '연료 소매',
  '오락용품 소매',
  '욕탕·신체관리',
  '운송장비 대여',
  '유원지·오락',
  '음료 소매',
  '의약·화장품 소매',
  '의원',
  '이용·미용',
  '인쇄·제품제작',
  '일반 교육',
  '일반 숙박',
  '일식',
  '자동차 부품 소매',
  '자동차 수리·세차',
  '장례식장 ',
  '장식품 소매',
  '전문 디자인',
  '조경·유지',
  '종합 소매',
  '주점',
  '중고 상품 소매',
  '중식',
  '철물·건설자재 소매',
  '청소·방제',
  '컴퓨터 수리',
  '통신장비 수리',
  '한식',
  '회계·세무'},
 75)

In [13]:
pd.options.display.max_columns = len(df.columns)

In [14]:
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA0101202210A0089715,날으는뚝배기원창점,NaN,I2,음식,I201,한식,I20102,국/탕/찌개류,I56111,한식 일반 음식점업,28,인천광역시,28260,서구,28260575,신현원창동,2826011100,원창동,2826011100103810048,1,대지,381.0,48.0,인천광역시 서구 원창동 381-48,282604790432,인천광역시 서구 북항로32번안길,41,NaN,2826011100103810048000001,건원프라자,인천광역시 서구 북항로32번안길 41,404210,22769,NaN,NaN,NaN,126.646684,37.509518
1,MA010120220805430815,아기숟가락,NaN,I2,음식,I201,한식,I20105,국수/칼국수,I56194,김밥 및 기타 간이 음식점업,28,인천광역시,28185,연수구,28185850,송도4동,2818510600,송도동,2818510600100830000,1,대지,83.0,NaN,인천광역시 연수구 송도동 83,281852152002,인천광역시 연수구 아트센터대로,203,NaN,2818510600100830000000001,송도센트럴파크푸르지오시티,인천광역시 연수구 아트센터대로 203,406840,22008,NaN,1,NaN,126.631272,37.395189
2,MA010120220805430978,러블리헤어,NaN,S2,수리·개인,S207,이용·미용,S20701,미용실,S96112,두발 미용업,28,인천광역시,28200,남동구,28200551,간석4동,2820010200,간석동,2820010200106170024,1,대지,617.0,24.0,인천광역시 남동구 간석동 617-24,282002008007,인천광역시 남동구 경원대로,962,NaN,2820010200106170024006353,신원아침도시비,인천광역시 남동구 경원대로 962,405810,21502,NaN,1,NaN,126.690749,37.468792
3,MA010120220805430761,쉐프윤,NaN,I2,음식,I210,기타 간이,I21003,피자,I56192,"피자, 햄버거, 샌드위치 및 유사 음식점업",28,인천광역시,28177,미추홀구,28177530,숭의4동,2817710100,숭의동,2817710100100450003,1,대지,45.0,3.0,인천광역시 미추홀구 숭의동 45-3,281773151011,인천광역시 미추홀구 수봉로,20,NaN,2817010100100450003125288,NaN,인천광역시 미추홀구 수봉로 20,402812,22163,NaN,NaN,NaN,126.656146,37.464376
4,MA010120220805430901,The선재로59Street,NaN,I1,숙박,I101,일반 숙박,I10104,캠핑/글램핑,I55109,기타 일반 및 생활 숙박시설 운영업,28,인천광역시,28720,옹진군,28720360,영흥면,2872036023,영흥면,2872036023101500000,1,대지,150.0,NaN,인천광역시 옹진군 영흥면 선재리 150,287203158017,인천광역시 옹진군 영흥면 선재로,59,NaN,2872036023101500000000001,NaN,인천광역시 옹진군 영흥면 선재로 59,409872,23123,NaN,NaN,NaN,126.531273,37.234406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113656,MA0101202307A0013333,상큼한과일,NaN,G2,소매,G205,식료품 소매,G20506,채소/과일 소매업,G47215,"채소, 과실 및 뿌리작물 소매업",28,인천광역시,28177,미추홀구,28177530,숭의4동,2817710100,숭의동,2817710100100530018,1,대지,53.0,18.0,인천광역시 미추홀구 숭의동 53-18,281773000028,인천광역시 미추홀구 경인로,126,NaN,2817010100106330025125031,NaN,인천광역시 미추홀구 경인로 126,402812,22164,NaN,1,NaN,126.656672,37.465959
113657,MA0101202307A0023409,힐링,NaN,G2,소매,G215,의약·화장품 소매,G21503,화장품 소매업,G47813,"화장품, 비누 및 방향제 소매업",28,인천광역시,28245,계양구,28245614,계산4동,2824510200,계산동,2824510200110630004,1,대지,1063.0,4.0,인천광역시 계양구 계산동 1063-4,282454265056,인천광역시 계양구 계산새로65번길,9,NaN,2824510200110630004176960,두손파스텔,인천광역시 계양구 계산새로65번길 9,407813,21060,NaN,NaN,NaN,126.735211,37.539097
113658,MA0101202307A0106428,석남마사지,NaN,S2,수리·개인,S208,욕탕·신체관리,S20803,체형/비만 관리,S96129,체형 등 기타 신체 관리 서비스업,28,인천광역시,28260,서구,28260560,석남2동,2826011000,석남동,2826011000105910013,1,대지,591.0,13.0,인천광역시 서구 석남동 591-13,282603156048,인천광역시 서구 석남로,70,1.0,2826011000105910013018226,NaN,인천광역시 서구 석남로 70-1,404829,22795,NaN,2,NaN,126.669370,37.500810
113659,MA0101202307A0024831,아수라떡볶이,NaN,I2,음식,I210,기타 간이,I21007,김밥/만두/분식,I56111,한식 일반 음식점업,28,인천광역시,28177,미추홀구,28177610,도화2.3동,2817710400,도화동,2817710400100940001,1,대지,94.0,1.0,인천광역시 미추홀구 도화동 94-1,281773151030,인천광역시 미추홀구 석정로,228,NaN,2817010500100940001061684,NaN,인천광역시 미추홀구 석정로 228,402806,22102,NaN,1,NaN,126.660830,37.467961
113660,MA0101202307A0045892,정석갈비,NaN,I2,음식,I201,한식,I20107,돼지고기 구이/찜,I56111,한식 일반 음식점업,28,인천광역시,28260,서구,28260710,당하동,2826011400,당하동,2826011400110810002,1,대지,1081.0,2.0,인천광역시 서구 당하동 1081-2,282604268839,인천광역시 서구 청마로51번안길,18,NaN,2826011400110810002000001,NaN,인천광역시 서구 청마로51번안길 18,404310,22675,NaN,1,NaN,126.672487,37.591650

In [15]:
df.columns

Index(['상가업소번호', '상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드',
       '상권업종중분류명', '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드',
       '시도명', '시군구코드', '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드',
       '대지구분코드', '대지구분명', '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지',
       '건물부번지', '건물관리번호', '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보',
       '호정보', '경도', '위도'],
      dtype='object')

In [16]:
df = df[['상호명','상권업종대분류명','상권업종중분류명','상권업종소분류명','지번주소','건물명']]

In [17]:
df

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,지번주소,건물명
0,날으는뚝배기원창점,음식,한식,국/탕/찌개류,인천광역시 서구 원창동 381-48,건원프라자
1,아기숟가락,음식,한식,국수/칼국수,인천광역시 연수구 송도동 83,송도센트럴파크푸르지오시티
2,러블리헤어,수리·개인,이용·미용,미용실,인천광역시 남동구 간석동 617-24,신원아침도시비
3,쉐프윤,음식,기타 간이,피자,인천광역시 미추홀구 숭의동 45-3,NaN
4,The선재로59Street,숙박,일반 숙박,캠핑/글램핑,인천광역시 옹진군 영흥면 선재리 150,NaN
...,...,...,...,...,...,...
113656,상큼한과일,소매,식료품 소매,채소/과일 소매업,인천광역시 미추홀구 숭의동 53-18,NaN
113657,힐링,소매,의약·화장품 소매,화장품 소매업,인천광역시 계양구 계산동 1063-4,두손파스텔
113658,석남마사지,수리·개인,욕탕·신체관리,체형/비만 관리,인천광역시 서구 석남동 591-13,NaN
113659,아수라떡볶이,음식,기타 간이,김밥/만두/분식,인천광역시 미추홀구 도화동 94-1,NaN
113660,정석갈비,음식,한식,돼지고기 구이/찜,인천광역시 서구 당하동 1081-2,NaN

In [18]:
df.isna().sum() # 건물명 결측치 개수 확인

상호명             0
상권업종대분류명        0
상권업종중분류명        0
상권업종소분류명        0
지번주소            0
건물명         63570
dtype: int64

In [19]:
df.isnull().sum()

상호명             0
상권업종대분류명        0
상권업종중분류명        0
상권업종소분류명        0
지번주소            0
건물명         63570
dtype: int64

In [20]:
df = df.fillna('') # NaN 값을 '' 로 대체

In [21]:
df

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,지번주소,건물명
0,날으는뚝배기원창점,음식,한식,국/탕/찌개류,인천광역시 서구 원창동 381-48,건원프라자
1,아기숟가락,음식,한식,국수/칼국수,인천광역시 연수구 송도동 83,송도센트럴파크푸르지오시티
2,러블리헤어,수리·개인,이용·미용,미용실,인천광역시 남동구 간석동 617-24,신원아침도시비
3,쉐프윤,음식,기타 간이,피자,인천광역시 미추홀구 숭의동 45-3,
4,The선재로59Street,숙박,일반 숙박,캠핑/글램핑,인천광역시 옹진군 영흥면 선재리 150,
...,...,...,...,...,...,...
113656,상큼한과일,소매,식료품 소매,채소/과일 소매업,인천광역시 미추홀구 숭의동 53-18,
113657,힐링,소매,의약·화장품 소매,화장품 소매업,인천광역시 계양구 계산동 1063-4,두손파스텔
113658,석남마사지,수리·개인,욕탕·신체관리,체형/비만 관리,인천광역시 서구 석남동 591-13,
113659,아수라떡볶이,음식,기타 간이,김밥/만두/분식,인천광역시 미추홀구 도화동 94-1,
113660,정석갈비,음식,한식,돼지고기 구이/찜,인천광역시 서구 당하동 1081-2,

In [22]:
df_food = df[df['상권업종대분류명'] == '음식']

In [23]:
df_food

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,지번주소,건물명
0,날으는뚝배기원창점,음식,한식,국/탕/찌개류,인천광역시 서구 원창동 381-48,건원프라자
1,아기숟가락,음식,한식,국수/칼국수,인천광역시 연수구 송도동 83,송도센트럴파크푸르지오시티
3,쉐프윤,음식,기타 간이,피자,인천광역시 미추홀구 숭의동 45-3,
6,불리다푸드,음식,한식,백반/한정식,인천광역시 남동구 논현동 665-4,
11,우리식당,음식,기타 간이,김밥/만두/분식,인천광역시 미추홀구 도화동 88-27,대훈아트빌
...,...,...,...,...,...,...
113647,럭셔리노래클럽,음식,주점,일반 유흥 주점,인천광역시 부평구 부평동 546-143,
113650,공화춘삼성바이오로직스점,음식,중식,중국집,인천광역시 연수구 송도동 201-2,삼성바이오로직스
113654,제주밤바다,음식,한식,백반/한정식,인천광역시 남동구 구월동 1369-2,
113659,아수라떡볶이,음식,기타 간이,김밥/만두/분식,인천광역시 미추홀구 도화동 94-1,
113660,정석갈비,음식,한식,돼지고기 구이/찜,인천광역시 서구 당하동 1081-2,

In [24]:
df_korea=df[df['상권업종중분류명'] == '한식']
df_china=df[df['상권업종중분류명'] == '중식']
df_japan=df[df['상권업종중분류명'] == '일식']

In [25]:
df_korea = df_korea.reset_index()
df_japan = df_japan.reset_index()
df_china = df_china.reset_index()

In [26]:
df_korea = df_korea.drop('index', axis=1)
df_japan = df_japan.drop('index', axis=1)
df_china = df_china.drop('index', axis=1)

In [27]:
df_korea

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,지번주소,건물명
0,날으는뚝배기원창점,음식,한식,국/탕/찌개류,인천광역시 서구 원창동 381-48,건원프라자
1,아기숟가락,음식,한식,국수/칼국수,인천광역시 연수구 송도동 83,송도센트럴파크푸르지오시티
2,불리다푸드,음식,한식,백반/한정식,인천광역시 남동구 논현동 665-4,
3,건강밥상심마니,음식,한식,백반/한정식,인천광역시 연수구 송도동 22-5,세종프라자
4,돈사미,음식,한식,돼지고기 구이/찜,인천광역시 서구 검암동 627-2,
...,...,...,...,...,...,...
15312,돼로변,음식,한식,백반/한정식,인천광역시 중구 운서동 3093-8,수린나오피스텔
15313,정성밥상,음식,한식,백반/한정식,인천광역시 계양구 임학동 71-7,
15314,송도주물럭,음식,한식,돼지고기 구이/찜,인천광역시 연수구 송도동 21-60,인천송도힐스테이트
15315,제주밤바다,음식,한식,백반/한정식,인천광역시 남동구 구월동 1369-2,
15316,정석갈비,음식,한식,돼지고기 구이/찜,인천광역시 서구 당하동 1081-2,

In [28]:
set(df_china['상권업종소분류명'])

{'마라탕/훠궈', '중국집'}

In [29]:
set(df_korea['상권업종소분류명'])

{'곱창 전골/구이',
 '국/탕/찌개류',
 '국수/칼국수',
 '기타 한식 음식점',
 '냉면/밀면',
 '닭/오리고기 구이/찜',
 '돼지고기 구이/찜',
 '백반/한정식',
 '복 요리 전문',
 '소고기 구이/찜',
 '전/부침개',
 '족발/보쌈',
 '해산물 구이/찜',
 '횟집'}

In [30]:
set(df_japan['상권업종소분류명'])

{'기타 일식 음식점', '일식 면 요리', '일식 카레/돈가스/덮밥', '일식 회/초밥'}

In [31]:
df_china[df['상권업종소분류명'] == '중국집']

C:\Users\4005\AppData\Local\Temp\ipykernel_19544\1698427342.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_china[df['상권업종소분류명'] == '중국집']

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,지번주소,건물명
175,동춘동양꼬치,음식,중식,중국집,인천광역시 연수구 동춘동 936-6,맘모스빌딩
239,중국전통마라탕.마라향궈,음식,중식,중국집,인천광역시 중구 운서동 3109-3,
266,마수리마라탕,음식,중식,마라탕/훠궈,인천광역시 서구 심곡동 298-4,
409,짜미옥중화요리,음식,중식,중국집,인천광역시 서구 당하동 1033-3,조이빌
417,중국관,음식,중식,중국집,인천광역시 부평구 산곡동 263-15,
751,태양푸드목향지점,음식,중식,중국집,인천광역시 연수구 송도동 10-110,
802,이화원,음식,중식,중국집,인천광역시 옹진군 백령면 진촌리 744-1,이화원
929,사오성,음식,중식,중국집,인천광역시 부평구 산곡동 370-399,현대아파트
964,중화명가,음식,중식,중국집,인천광역시 부평구 부개동 131-14,
979,팔진향한옥엔타스에스디,음식,중식,중국집,인천광역시 연수구 송도동 24-17,
1050,대형각,음식,중식,중국집,인천광역시 미추홀구 숭의동 341-32,
1056,대명각,음식,중식,중국집,인천광역시 남동구 만수동 882-14,
1100,진짜루,음식,중식,중국집,인천광역시 남동구 간석동 616-7,신동아파밀리에명품아파트
1160,용팔이양꼬치,음식,중식,중국집,인천광역시 남동구 만수동 911,
1245,일등짬뽕,음식,중식,중국집,인천광역시 중구 운남동 438-1,
1451,레드문츠츠허허,음식,중식,중국집,인천광역시 연수구 송도동 176-1,송도트리플스트리트
1514,양꼬치품격,음식,중식,중국집,인천광역시 부평구 부평동 150-40,
1573,황비홍마라탕인천대3,음식,중식,마라탕/훠궈,인천광역시 연수구 송도동 13-58,